OvmfPkg: suppress "Value stored to ... is never read" analyzer warnings
RH covscan warns about assignments that it can determine are never
"consumed" later ("dead stores"). The idea behind the warning is
presumably that the programmer forgot to implement a dependent check
somewhere.

For each such warning that has been emitted for OvmfPkg,
the case is one of the following however:

- We assign a variable a value for (re-)initialization's sake, in
  preparation for further or future uses. This practice is safe (sometimes
  even recommended!), hence we should suppress these warnings.

- We capture a result or a computation in a variable, following a general
  programming pattern, but then decide to ignore the value in that
  particular case. This is again safe, and we should suppress these
  warnings too.

According to the Clang documentation at

  https://clang-analyzer.llvm.org/faq.html#dead_store

we should use

  (void)x;

See the logs below (produced originally for edk2-stable201903).

> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/AcpiPlatformDxe/Xen.c:156:3: warning: Value
> stored to 'NumberOfTableEntries' is never read
> #  NumberOfTableEntries = 0;
> #  ^                      ~
> edk2-89910a39dcfd/OvmfPkg/AcpiPlatformDxe/Xen.c:156:3: note: Value
> stored to 'NumberOfTableEntries' is never read
> #  NumberOfTableEntries = 0;
> #  ^                      ~
> #  154|     DsdtTable   = NULL;
> #  155|     TableHandle = 0;
> #  156|->   NumberOfTableEntries = 0;
> #  157|
> #  158|     //
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/Library/PlatformBootManagerLib/QemuKernel.c:43:3:
> warning: Value stored to 'SetupSize' is never read
> #  SetupSize = 0;
> #  ^           ~
> edk2-89910a39dcfd/OvmfPkg/Library/PlatformBootManagerLib/QemuKernel.c:43:3:
> note: Value stored to 'SetupSize' is never read
> #  SetupSize = 0;
> #  ^           ~
> #   41|
> #   42|     SetupBuf = NULL;
> #   43|->   SetupSize = 0;
> #   44|     KernelBuf = NULL;
> #   45|     KernelInitialSize = 0;
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/Library/SerializeVariablesLib/SerializeVariablesLib.c:609:9:
> warning: Value stored to 'VariableDataBufferSize' is never read
> #        VariableDataBufferSize = 0;
> #        ^                        ~
> edk2-89910a39dcfd/OvmfPkg/Library/SerializeVariablesLib/SerializeVariablesLib.c:609:9:
> note: Value stored to 'VariableDataBufferSize' is never read
> #        VariableDataBufferSize = 0;
> #        ^                        ~
> #  607|           FreePool (VariableData);
> #  608|           VariableData = NULL;
> #  609|->         VariableDataBufferSize = 0;
> #  610|         }
> #  611|         VariableData = AllocatePool (VariableDataSize);
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/Library/VirtioLib/VirtioLib.c:125:3: warning:
> Value stored to 'RingPagesPtr' is never read
> #  RingPagesPtr += sizeof *Ring->Used.AvailEvent;
> #  ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> edk2-89910a39dcfd/OvmfPkg/Library/VirtioLib/VirtioLib.c:125:3: note:
> Value stored to 'RingPagesPtr' is never read
> #  RingPagesPtr += sizeof *Ring->Used.AvailEvent;
> #  ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> #  123|
> #  124|     Ring->Used.AvailEvent = (volatile VOID *) RingPagesPtr;
> #  125|->   RingPagesPtr += sizeof *Ring->Used.AvailEvent;
> #  126|
> #  127|     Ring->QueueSize = QueueSize;
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockService.c:1079:3:
> warning: Value stored to 'FwhInstance' is never read
> #  FwhInstance = (EFI_FW_VOL_INSTANCE *)
> #  ^             ~~~~~~~~~~~~~~~~~~~~~~~
> edk2-89910a39dcfd/OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockService.c:1079:3:
> note: Value stored to 'FwhInstance' is never read
> #  FwhInstance = (EFI_FW_VOL_INSTANCE *)
> #  ^             ~~~~~~~~~~~~~~~~~~~~~~~
> # 1077|     ASSERT_RETURN_ERROR (PcdStatus);
> # 1078|
> # 1079|->   FwhInstance = (EFI_FW_VOL_INSTANCE *)
> # 1080|       (
> # 1081|         (UINTN) ((UINT8 *) FwhInstance) + FwVolHeader->HeaderLength +
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockServiceDxe.c:173:3:
> warning: Value stored to 'Status' is never read
> #  Status = gDS->RemoveMemorySpace (
> #  ^        ~~~~~~~~~~~~~~~~~~~~~~~~
> edk2-89910a39dcfd/OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockServiceDxe.c:173:3:
> note: Value stored to 'Status' is never read
> #  Status = gDS->RemoveMemorySpace (
> #  ^        ~~~~~~~~~~~~~~~~~~~~~~~~
> #  171|     // Mark flash region as runtime memory
> #  172|     //
> #  173|->   Status = gDS->RemoveMemorySpace (
> #  174|                     BaseAddress,
> #  175|                     Length
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/SataControllerDxe/SataController.c:231:3:
> warning: Value stored to 'DeviceUDmaMode' is never read
> #  DeviceUDmaMode = 0;
> #  ^                ~
> edk2-89910a39dcfd/OvmfPkg/SataControllerDxe/SataController.c:231:3:
> note: Value stored to 'DeviceUDmaMode' is never read
> #  DeviceUDmaMode = 0;
> #  ^                ~
> #  229|     UINT16    DeviceUDmaMode;
> #  230|
> #  231|->   DeviceUDmaMode = 0;
> #  232|
> #  233|     //
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/VirtioGpuDxe/Gop.c:65:5: warning: Value stored
> to 'Status' is never read
> #    Status = VirtioGpuSetScanout (
> #    ^        ~~~~~~~~~~~~~~~~~~~~~
> edk2-89910a39dcfd/OvmfPkg/VirtioGpuDxe/Gop.c:65:5: note: Value stored to
> 'Status' is never read
> #    Status = VirtioGpuSetScanout (
> #    ^        ~~~~~~~~~~~~~~~~~~~~~
> #   63|       // by setting ResourceId=0 for it.
> #   64|       //
> #   65|->     Status = VirtioGpuSetScanout (
> #   66|                  VgpuGop->ParentBus, // VgpuDev
> #   67|                  0, 0, 0, 0,         // X, Y, Width, Height
>
> Error: CLANG_WARNING:
> edk2-89910a39dcfd/OvmfPkg/VirtioNetDxe/SnpReceive.c:165:3: warning:
> Value stored to 'RxPtr' is never read
> #  RxPtr += sizeof (UINT16);
> #  ^        ~~~~~~~~~~~~~~~
> edk2-89910a39dcfd/OvmfPkg/VirtioNetDxe/SnpReceive.c:165:3: note: Value
> stored to 'RxPtr' is never read
> #  RxPtr += sizeof (UINT16);
> #  ^        ~~~~~~~~~~~~~~~
> #  163|       *Protocol = (UINT16) ((RxPtr[0] << 8) | RxPtr[1]);
> #  164|     }
> #  165|->   RxPtr += sizeof (UINT16);
> #  166|
> #  167|     Status = EFI_SUCCESS;

Cc: Anthony Perard <anthony.perard@citrix.com>
Cc: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Cc: Jordan Justen <jordan.l.justen@intel.com>
Cc: Julien Grall <julien.grall@arm.com>
Bugzilla: https://bugzilla.tianocore.org/show_bug.cgi?id=1710
Issue: scan-0992.txt
Issue: scan-0996.txt
Issue: scan-0997.txt
Issue: scan-0998.txt
Issue: scan-1000.txt
Issue: scan-1001.txt
Issue: scan-1006.txt
Issue: scan-1011.txt
Issue: scan-1012.txt
Signed-off-by: Laszlo Ersek <lersek@redhat.com>